name: "Snyk Code Test"
# Run workflow each time code is pushed to your repository.
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: snyk/actions/setup@master
      - name: Snyk Code Test
        run: snyk code test --sarif &> snyk-code.json
        continue-on-error: true       
        env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}    
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk-code.json
