name: "Snyk Code Action"
# Run workflow each time code is pushed to your repository.
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print github workspace
        run: |
          echo "GITHUB_WORKSPACE = $GITHUB_WORKSPACE"
          echo "github.workspace = ${{ github.workspace }}"
          echo "pr.ref = ${{github.event.pull_request.head.ref}}"
          echo "github.ref = ${{ github.ref }}"
      - uses: snyk/actions/setup@master
      - name: Snyk Code Action
        run: snyk code test --sarif &> results.sarif
        continue-on-error: true       
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: ${{ github.workspace }}
          replace: ""
          include: "results.sarif" 
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
