name: "Snyk Project Delete"
on:
  pull_request:
    branches: 
      - main
    types: [ closed ]
jobs:
  snyk-project-delete:
    # this job will only run if the PR has been merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2   
      - name: Snyk Branch Delete
        run:  sh .github/workflows/scripts/snyk-project-delete.sh
        env:
            REPOSITORY: ${{ github.event.repository.name }}
            HEAD_REF: ${{ github.head_ref }}
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
            SNYK_ORG: ${{ secrets.SNYK_ORG }}
            SNYK_INTEGRATION_ID: ${{ secrets.SNYK_INTEGRATION_ID }}
