name: "Snyk Project Import"
# Run workflow each time code is pushed to your repository. 
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2   
      - name: Snyk Branch Import
        run:  | 
              chmod +x "${GITHUB_WORKSPACE}/.github/snyk-project-import.sh"
              "${GITHUB_WORKSPACE}/.github/snyk-project-import.sh"
        env:
            WORKSPACE: ${{ github.workspace }}
            OWNER: ${GITHUB_REPOSITORY}
            REPOSITORY: ${GITHUB_REPOSITORY}
            BRANCH_NAME: ${GITHUB_REF##*/}
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
            SNYK_INTEGRATION_ID: ${{ secrets.SNYK_INTEGRATION_ID }}
